//! Identifier types for `boa-sw` (TS §6.1).
//!
//! Identifiers are opaque `u64`-backed newtypes generated by [`IdAllocator`].

use core::fmt;

/// Declares an opaque, `u64`-backed identifier newtype.
///
/// Generated items: the struct, `from_raw`, `raw`, `Display` (as `<prefix>#<n>`),
/// `Copy`/`Clone`/`PartialEq`/`Eq`/`Hash`/`PartialOrd`/`Ord`/`Debug`.
macro_rules! define_id {
    ($name:ident, $prefix:expr) => {
        /// An opaque identifier.
        #[derive(Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
        pub struct $name(u64);

        impl $name {
            /// Creates an identifier from a raw `u64` value.
            #[must_use]
            pub const fn from_raw(raw: u64) -> Self {
                Self(raw)
            }

            /// Returns the raw `u64` value.
            #[must_use]
            pub const fn raw(self) -> u64 {
                self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}#{}", $prefix, self.0)
            }
        }
    };
}

define_id!(RegistrationId, "reg");
define_id!(WorkerId, "sw");
define_id!(JobId, "job");
define_id!(DispatchId, "dispatch");
define_id!(CacheId, "cache");

/// A host-assigned client identifier (TS `R6.1.2`, `R6.1.2a`).
///
/// Opaque: this crate never parses it, never generates one, and never reuses one.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Debug)]
pub struct ClientId(String);

impl ClientId {
    /// Creates a new `ClientId` from the given raw string.
    pub fn new(raw: impl Into<String>) -> Self {
        Self(raw.into())
    }

    /// Returns the client identifier as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ClientId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Monotonic id source (TS `R6.1.1`).
#[derive(Debug, Clone)]
pub struct IdAllocator {
    next: u64,
}

impl IdAllocator {
    /// Starts allocating at 1; `0` is never handed out and can be used as a "none" marker.
    #[must_use]
    pub const fn new() -> Self {
        Self { next: 1 }
    }

    /// Returns the next raw id.
    ///
    /// Uses `checked_add(1)` internally; exhausting `u64` is unreachable in practice
    /// (2^64 allocations), so on overflow it saturates and a `debug_assert!` fires.
    pub fn allocate(&mut self) -> u64 {
        let id = self.next;
        // Invariant: `next` is always > 0 after `new()`. On overflow, saturate to `u64::MAX`.
        self.next = self.next.checked_add(1).unwrap_or_else(|| {
            debug_assert!(false, "IdAllocator exhausted u64 range");
            u64::MAX
        });
        id
    }

    /// Continues above a persisted maximum: `next = max(next, max_seen + 1)` (TS `R6.1.1`).
    pub fn restore_from(&mut self, max_seen: u64) {
        let candidate = max_seen.saturating_add(1);
        if candidate > self.next {
            self.next = candidate;
        }
    }

    /// The id `allocate` would return next, without consuming it.
    #[must_use]
    pub const fn peek(&self) -> u64 {
        self.next
    }
}

impl Default for IdAllocator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn display_format() {
        assert_eq!(RegistrationId::from_raw(1).to_string(), "reg#1");
        assert_eq!(WorkerId::from_raw(42).to_string(), "sw#42");
        assert_eq!(JobId::from_raw(7).to_string(), "job#7");
        assert_eq!(DispatchId::from_raw(3).to_string(), "dispatch#3");
        assert_eq!(CacheId::from_raw(9).to_string(), "cache#9");
        assert_eq!(ClientId::new("abc").to_string(), "abc");
    }

    #[test]
    fn allocate_starts_at_one() {
        let mut alloc = IdAllocator::new();
        assert_eq!(alloc.peek(), 1);
        assert_eq!(alloc.allocate(), 1);
        assert_eq!(alloc.peek(), 2);
    }

    #[test]
    fn restore_from_continues_above_max() {
        let mut alloc = IdAllocator::new();
        alloc.restore_from(10);
        assert_eq!(alloc.allocate(), 11);

        // restore_from(3) on an allocator already at 12 does NOT move it backwards
        alloc.restore_from(3);
        assert_eq!(alloc.allocate(), 12);
    }

    #[test]
    fn default_matches_new() {
        assert_eq!(IdAllocator::default().peek(), IdAllocator::new().peek());
        assert_eq!(IdAllocator::default().peek(), 1);
    }
}
